### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by souravsk** [dev-aniketj/WeatherApp-Android#6]
Hey, @dev-aniketj Your Project is really lovely I'm using this project for my college project the problem is that when I use the API that I created using my email id is not working but when I use your API which is being Commanded just above API_KEY variable. 
Could you please let me know what's the reason for that?

**Comment by dev-aniketj** [comment]
Please use this link to get the data - https://api.openweathermap.org/data/2.5/onecall?exclude=minutely&lat=26.9124&lon=75.7873&appid=API_KEY
(API_KEY replace with your api key)

Sometimes it takes 2-4 days for new api, please generate another one if the previous is not working, and wait atleast 2-3 hours to get service started.
@souravsk

**Comment by souravsk** [comment]
okay Thanks, @dev-aniketj just one more thing by any chance do you have documentation for this project? Like DFD, ER, etc

**Comment by dev-aniketj** [comment]
No I did not create one, because all the instructions are already given on the website [Open Weather Map](https://openweathermap.org/)

Documentation for the Weather App Link - [Official Docs](https://openweathermap.org/current)
